### ISSUE TITLE
IE-Fade transition plugin - IE7 & IE8 bug - hides image slides the n-th time you navigate to them

### ISSUE THREAD

**Issue by chrisjacob** [malsup/cycle2#289]
I added the "ie-fade" transition plugin hoping it would magically fix any IE issues with fade transitions. But it actually introduced a bug (in my case anyway - others might not experience this).

With the plugin enabled, with a slideshow containing images, I could navigate forwards just fine. The "fadeout" worked beautifully. But when I navigated backwards, or re-navigated to any of the slides again (e.g. via pager). The Image being navigated to would display in full opacity for the transition "speed", then completely disappear.

Has something to do with:

``` javascript
try { el.style.removeAttribute('filter'); }
```

I've removed the ie-fade plugin and now everything is working fine. 

p.s. I'm dealing with image slides, and not text slides - which I now realise is what this plugin aims to help fix up - something to do with ClearType... I just didn't expect it to harm my image slideshow ;-)

"IE-Fade" it's the only plugin without a demo (http://jquery.malsup.com/cycle2/download/) - would be great if you could setup a demo page to explain when this plugin is useful ... and when it may be harmful (it might not normally be harmful).

p.p.s My CSS for the img slides:

``` css
.cycle-slideshow img { 
  position: absolute; 
  top: 0; 
  left: 0;
  max-width: 100%; 
  padding: 0; 
  display: block;
}
```

and the Cycle "slide-css" is set to the default

``` css
{ position: 'absolute', top: 0, left: 0 }
```

p.p.p.s

Tested in IE10 on Windows 8, using F12 tools to set Browser Mode: IE7/8 and Document Mode: IE7/8 standards.
